eventDb:
  file: ${DB_FILE:-resources/event-db/event_db.db}
  name: ${DB_NAME:-event_db}
  migrationLoc: ${DB_MIGRATION_LOC:-migrations}
  maxConnection: ${DB_MAX_CONN:-200}
server:
  port: ${SERVER_PORT:-3000}
ipGeoDbConfig:
  location: ${IP_GEO_DB_LOC:-resources/geo-database/GeoLite2-City.mmdb}
  maxConnection: ${IP_GEO_DB_MAX_CONN:-200}
suspiciousSpeed: ${SUSPICIOUS_SPEED:-100}
